import{S as y,i as g}from"./assets/vendor-5b791d57.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const s of r.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&i(s)}).observe(document,{childList:!0,subtree:!0});function c(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=c(e);fetch(e.href,r)}})();const L="https://pixabay.com/api/",b="41991385-9b19b8bb3d6f1491499417d17",o={form:document.querySelector(".form"),input:document.querySelector(".input"),gallery:document.querySelector(".gallery"),loader:document.querySelector(".loader"),searchBtn:document.querySelector(".button")};o.form.addEventListener("submit",l=>{l.preventDefault();const n=o.input.value.trim();if(!n){r("The search field can't be empty! Please, enter your request!");return}const c=`${L}?key=${b}&q=${n}&image_type=photo&orientation=horizontal&safesearch=true`;function i(t){return s(!0),fetch(t).then(a=>{if(!a.ok)throw new Error(a.statusText);return a.json()})}i(c).then(t=>{t.hits.length===0&&(r("Sorry, there are no images matching your search query. Please, try again!"),s(!1)),o.gallery.innerHTML=e(t.hits),s(!1),new y(".gallery-item a",{captionsData:"alt",captionDelay:250}),o.form.reset()}).catch(t=>console.error(t));function e(t){return t.map(({webformatURL:a,largeImageURL:u,tags:d,likes:f,views:p,comments:m,downloads:h})=>`
        <li class="gallery-item">
          <a class="gallery-link" href="${u}">
          <img
            class="gallery-image"
            src="${a}"
            alt="${d}"
          />
            <p class="gallery-descr">Likes: <span class="descr-span">${f}</span> Views: <span class="descr-span">${p}</span> Comments: <span class="descr-span">${m}</span> Downloads: <span class="descr-span">${h}</span></p>
          </a>
        </li>`).join("")}function r(t){g.show({class:"error-svg",position:"topRight",icon:"error-svg",message:t,maxWidth:"432",messageColor:"#fff",messageSize:"16px",backgroundColor:"#EF4040",close:!1,closeOnClick:!0})}function s(){o.loader.classList.remove("hidden")}});
//# sourceMappingURL=commonHelpers.js.map
